### ISSUE TITLE
Can I use functional api with vuex?

### ISSUE THREAD

**Issue by mspoulsen** [vuejs/vue-function-api#18] opened 2019-07-02 06:22 UTC
Hi,

I am really eager to try this new api and especially the typescript integration. But can I use this api with vuex? If so could anybody provide an example? :slightly_smiling_face: 

Thanks!

**Comment by a9** [comment] 2019-07-02 06:48
> Hi,
> 
> I am really eager to try this new api and especially the typescript integration. But can I use this api with vuex? If so could anybody provide an example? 🙂
> 
> Thanks!

see comment https://github.com/vuejs/vue-function-api/issues/8#issuecomment-506143686

**Comment by SilentDepth** [comment] 2019-07-03 09:15
Actually, after splitting states into hooks, I removed vuex from my project dependencies. 🤪

**Comment by u3u** [comment] 2019-07-08 17:28
Hi, everyone, I created a [vue-hooks](https://github.com/u3u/vue-hooks) repository and [package](https://www.npmjs.com/package/@u3u/vue-hooks).
It contains commonly used hooks (e.g: `vuex` / `vue-router`).
Documentation has not been written yet, welcome everyone to contribute! 😄

**Comment by gianko** [comment] 2019-07-18 15:34
@SilentDepth how are you sharing sharing `vue-function-api` state between components?

care to share an example? please

**Comment by SilentDepth** [comment] 2019-07-18 15:51
@gianko Just like this:

```js
/* hook-msg.js */

import {value as binding} from 'vue-function-api'

const msg = binding('hello world')

export default function useMsg () {
  return {
    msg,
  }
}
```

```js
/* comp-a.vue */

import useMsg from './hook-msg'

export default {
  setup () {
    const {msg} = useMsg()

    return {
      msg,
    }
  },
}
```

```js
/* comp-b.vue */

import {computed} from 'vue-function-api'
import useMsg from './hook-msg'

export default {
  setup () {
    const {msg} = useMsg()

    return {
      msgUpperCased: computed(() => msg.value.toUpperCase()),
    }
  },
}
```

**Comment by gianko** [comment] 2019-07-18 16:00
Thanks!... I was getting an error about using vue function api before calling the use plugin.

**Comment by thommath** [comment] 2019-07-25 13:10
I used the trick in the [#8 answer](https://github.com/vuejs/vue-function-api/issues/8#issuecomment-506143686) but built on it a bit by making a small vuex plugin to do the wrapping of my getters.

Feels kind of hacky, but then all getters can be unpacked in one line

```javascript
/* store-plugin.js */
import { computed } from 'vue-function-api'

let getters = {};

const myPlugin = store => {
  Object.keys(store.getters)
    .forEach(key => (getters[key] = computed(() => store.getters[key])));
}

export {
  myPlugin,
  getters
};
```

Then the computed getters can be accessed with:

```javascript
/* some-vue-file.vue */
import { getters } from './store-plugin.vue';

const { someGetter, someOtherGetter } = getters;
```

**Comment by furryablack** [comment] 2019-07-27 07:43
What do you think about https://github.com/zerobias/effector as a state manager?

Vue-function-api is the great thing with jsx =)
I thinking vuex doesn't need anymore =D

See:

```js
// @app/core/hooks/use-value
import { value } from "vue-function-api"

export const useValue = (initialValue, lazy) => {
  lazy = !!lazy
  const state = value(initialValue)
  const dispatch = (newValue) => {
    if (!lazy) {
      state.value = newValue
    } else if (state.value !== newValue) {
      state.value = newValue
    }
  }
  const reset = () => dispatch(initialValue)
  return [state, dispatch, reset]
}

// @app/core/hooks/use-reducer
import { useValue } from "./use-value"

export const useReducer = (reducer, initialValue, lazy) => {
  const [state, set, reset] = useValue(initialValue, lazy)
  const dispatch = (payload) => {
    const reducerResult = reducer(state.value, payload)
    set(reducerResult)
  }
  return [state, dispatch, reset]
}
```

Example:
```js
import { useReducer } from "@app/core/hooks/use-reducer"

export const ExampleCounter = {
  setup() {
    const initialValue = 0

    function reducer(value, payload) {
      switch (payload.type) {
        case "increment":
          return value + 1
        case "decrement":
          return value - 1
        default:
          throw new Error()
      }
    }

    const [count, updateCount, reset] = useReducer(reducer, initialValue)

    const increment = () => updateCount({ type: "increment" })
    const decrement = () => updateCount({ type: "decrement" })

    // No needs, we have reset state function already
    // const reset = () => updateCount({ type: "reset" })

    return {
      count,
      increment,
      decrement,
      reset,
    }
  },

  render(h) {
    return (
      <div>
        Count: {this.counter.toString()}
        <button vOn:click_prevent={this.increment}>+</button>
        <button vOn:click_prevent={this.decrement}>-</button>
        <button vOn:click_prevent={this.reset}>reset</button>
      </div>
    )
  },
}
```

PS: 
Example uses jsx - vue requires the next babel plugins for that
```js
{
  plugins: [
    "@vue/babel-plugin-transform-vue-jsx",
    "@vue/babel-sugar-v-on",
  ]
}
```

**Comment by posva** [comment] 2019-07-31 10:56
Duplicate of #8

**Closed by posva** 2019-07-31 10:56 UTC

**Comment by blowsie** [comment] 2019-12-05 15:09
@SilentDepth i presume this example is not still relevant?
I tried to do the equivalent using ref and got an error `Uncaught Error: [vue-composition-api] must call Vue.use(plugin) before using any function.`


> @gianko Just like this:
> 
> ```js
> /* hook-msg.js */
> 
> import {value as binding} from 'vue-function-api'
> 
> const msg = binding('hello world')
> 
> export default function useMsg () {
>   return {
>     msg,
>   }
> }
> ```
> 
> ```js
> /* comp-a.vue */
> 
> import useMsg from './hook-msg'
> 
> export default {
>   setup () {
>     const {msg} = useMsg()
> 
>     return {
>       msg,
>     }
>   },
> }
> ```
> 
> ```js
> /* comp-b.vue */
> 
> import {computed} from 'vue-function-api'
> import useMsg from './hook-msg'
> 
> export default {
>   setup () {
>     const {msg} = useMsg()
> 
>     return {
>       msgUpperCased: computed(() => msg.value.toUpperCase()),
>     }
>   },
> }
> ```

**Comment by SilentDepth** [comment] 2019-12-06 10:54
@blowsie You need to call `Vue.use()` first, before any composition api being used.

The missing entry file of my example:

```js
/* main.js */

import Vue from 'vue'
import './use-composition-api'
import App from './app.vue'

new Vue({
  render: h => h(App),
})
```

```js
/* use-composition-api.js */

import Vue from 'vue'
import CompositionApi from '@vue/composition-api'

Vue.use(CompositionApi)
```
